### ISSUE TITLE
PDF Style disappears

### ISSUE THREAD

**Issue by felipedantas-pi** [MuiseDestiny/zotero-style#933] opened 2024-04-04 12:37 UTC
**Versão Zotero**: 7.0.0-beta.68+c31a40c74 (64-bit)
**Versão Ethereal Style**: 4.2.7.4

My plugin is updating to the version indicated above, and it no longer works with the *PDF Style* function. To fix this, I need to downgrade to version 4.2.1

![image](https://github.com/MuiseDestiny/zotero-style/assets/69129407/f3e4f0af-1771-4ae2-ae40-705f3f376f7d)

**Comment by saligari** [comment] 2024-04-11 07:21
Had the same issue, today's update (4.3.2) solved this for me. If it's solved for you as well please comment so we can close the issue.

**Comment by Exilioloz** [comment] 2024-04-11 07:32
Yep the problem is solved for me, thx.

**Closed** 2024-04-11 07:37 UTC
